acgg/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from django.conf import settings

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'acgg.views.home', name='home'),
    # url(r'^acgg/', include('acgg.foo.urls')),

    #Django allauth
    (r'^accounts/', include('allauth.urls')),
    # url(r'^$', TemplateView.as_view(template_name='index.html')),
	url(r'^accounts/profile/$', TemplateView.as_view(template_name='profile.html')),

	#Django Avatar
	(r'^avatar/', include('avatar.urls')),	

    #Django Smart Selectors
    url(r'^chaining/', include('smart_selects.urls')),
 
    #My booking app
    #url(r'^booking/',include('booking.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    
    #Need to be last
    url(r'^', include('cms.urls')),
)


if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    url(r'', include('django.contrib.staticfiles.urls')),
) + urlpatterns

booking/urls.py
from django.conf.urls import patterns, url

from booking.views import ParticipantCreate, ParticipantUpdate, ParticipantDelete, ParticipantDetail
from booking.views import EventList, EventDetail

urlpatterns = patterns('booking.views',
	url(r'events/', EventList.as_view(), name = 'event_list'),
	url(r'event/(?P<pk>\d+)/$', EventDetail.as_view(), name = 'event_detail'),

    url(r'add/(?P<event_id>\d+)/$', ParticipantCreate.as_view(), name = 'participant_add'),
    url(r'delete/(?P<pk>\d+)/$', ParticipantDelete.as_view(), name = 'participant_delete'),
    url(r'edit/(?P<pk>\d+)/$', ParticipantUpdate.as_view(), name = 'participant_update'),
	url(r'(?P<pk>\d+)/$', ParticipantDetail.as_view(), name = 'participant_detail')
)

booking/models.py
from django.db import models
from django.core.urlresolvers import reverse
from smart_selects.db_fields import ChainedForeignKey 
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from cms.models import CMSPlugin

import datetime

class EventPlugin(CMSPlugin):
    """ Make this a CMSPlugins """
    event = models.ForeignKey('booking.Event', related_name='plugins')

    def __unicode__(self):
      return self.event.name


class Event(models.Model):
    """ This describ the event in question """

    class Meta:
        db_table = "booking_event"
        verbose_name = _("Event")
        verbose_name_plural = _("Events")


    name = models.CharField(
        max_length = 150, 
        help_text = _("The name of the event"),
        unique = True
        )

    description = models.TextField(
        help_text = _("Describe the event"),
        null = True,
        blank = True
        )

    start_date = models.DateField(
        help_text = _("Start date of the Event")
        )

    end_date = models.DateField(
        help_text = _("End date of the Event")
        )

    def _participants(self):
        return Event.objects.get(pk = self.pk ).participant_set.values_list('user__username', flat = True)

    participants = property(_participants)

    def _dates(self):
        dates = []
        my_date = self.start_date
        while my_date <= self.end_date:
            dates.append(my_date)
            my_date = my_date + datetime.timedelta(days = 1)

        return dates

    dates = property(_dates)


    def __unicode__(self):
        return "%s"  % (self.name)


class ParticipantLevel(models.Model):
    """ 
    To what level can you perticitate to this event.
    For ACG-G this would normaly be:
       - Visitor : price 20kr
       - No computer : price 80kr
       - With computer: price 100kr

    This is needed as the price will change from year to year. 

    """

    class Meta:
        db_table = "booking_participant_level"
        verbose_name = _("Participant Level")
        verbose_name_plural = _("Participant Levels")

    description = models.CharField( 
        max_length = 50,
        help_text = _("Describe the level of participation, it could be: With Computer, Without computer space")
        )

    price = models.PositiveSmallIntegerField(
        help_text = _("The price for this level")
        )
    
    event = models.ForeignKey('Event', 
        help_text = _("To what event do this affect")
        )

    def __unicode__(self):
        return "%s - %s kr"  % (self.description, self.price)


class Participant(models.Model):
    """
    Who will attend this event.

    """

    class Meta:
        db_table = "booking_participant"
        verbose_name = _("Participant")
        verbose_name_plural = _("Participants")


    user = models.ForeignKey(User, 
        help_text = _("How is attending")
        )

    event = models.ForeignKey('Event', 
        help_text = _("What event to attend")
        )

    from_date = models.DateField(
        help_text = _("What date will you arraive?")
        )

    to_date = models.DateField(
        help_text = _("What date will you depart?")
        )

    level = ChainedForeignKey(ParticipantLevel,
        chained_field = "event",
        chained_model_field = "event", 
        show_all = False, 
        auto_choose = True,
        help_text = _("Particpate level")
        )

    def __unicode__(self):
        return "%s (%s - %s)"  % (self.user, self.from_date, self.to_date)

    def get_absolute_url(self):
        return reverse('participant_detail', kwargs={'pk': self.pk}) 

booking/forms.py
from django import forms
from django.utils.translation import ugettext as _
from django.core import exceptions
from booking import models as booking_models

class EventForm(forms.ModelForm):
    """
    Describe master Event form 
    """
    class Meta:
        model = booking_models.Event
        fields = ('name','description','start_date','end_date') 



class ParticipantLevelForm(forms.ModelForm):
    """
    Describe master ParticipantLevel form 
    """

    class Meta:
        model = booking_models.ParticipantLevel
        fields = ('description','price','event')


class ParticipantSmallForm(forms.ModelForm):
    """
    Describe Participant form 
    """

    class Meta:
        model = booking_models.Participant
        fields = ('event', 'from_date', 'to_date', 'level')
        widgets = {'event' : forms.HiddenInput()}


    def clean(self):
        my_to_date = self.cleaned_data.get('to_date')
        my_from_date = self.cleaned_data.get('from_date')
        my_event = self.cleaned_data.get('event')

        try: 
            event = booking_models.Event.objects.get(pk = my_event.id)
        except exceptions.ObjectDoesNotExist:
            raise forms.ValidationError(_("Invalid event given"))

        to_between = booking_models.Event.objects.filter(pk = my_event.id).filter(start_date__lte = my_to_date, end_date__gte = my_to_date)
        from_between = booking_models.Event.objects.filter(pk = my_event.id).filter(start_date__lte = my_from_date, end_date__gte = my_from_date)


        if len(to_between) == 0:
            msg = _(u"%s: Is invalid need to be between %s and %s" % (my_to_date, event.start_date, event.end_date))
            self._errors["to_date"] = self.error_class([msg])
            del self.cleaned_data['to_date']

        if len(from_between) == 0:
            msg = _(u"%s: Is invalid need to be between %s and %s" % (my_from_date, event.start_date, event.end_date))
            self._errors["from_date"] = self.error_class([msg])
            del self.cleaned_data['from_date']

        if self.cleaned_data.get('from_date') and self.cleaned_data.get('from_date'):
            #They might ber gone due to above conditions.
            if self.cleaned_data.get('from_date') > self.cleaned_data.get('to_date'): 
                #Fix the problem
                tmp = self.cleaned_data.get('to_date')
                self.cleaned_data['to_date'] = self.cleaned_data.get('from_date')
                self.cleaned_data['from_date'] = tmp

        cleaned_data = super(ParticipantSmallForm, self).clean()
        return cleaned_data


class ParticipantForm(forms.ModelForm):
    """
    Describe Participant form 
    """

    class Meta:
        model = booking_models.Participant
        fields = ('user','event','to_date', 'from_date','level')


    def clean(self):
        my_date = self.cleaned_data.get('to_date')
        my_event = self.cleaned_data.get('event')
        between = booking_models.Event.objects.filter(pk = my_event.id).filter(start_date__lte = my_date, end_date__gte = my_date)

        if len(between) == 0:
            
            try: 
                event = booking_models.Event.objects.get(pk = my_event.id)
                msg = _(u"%s: Is invalid need to be between %s and %s" % (my_date, event.start_date, event.end_date))
            except exceptions.ObjectDoesNotExist:
                msg = -(u"%s: Is not a valid date" % (my_date))

            self._errors["date"] = self.error_class([msg])
            del self.cleaned_data['date']
            #raise forms.ValidationError(_("Invalid date given for this event"))

        cleaned_data = super(ParticipantForm, self).clean()
        return cleaned_data

booking/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404

from booking.models import Event, Participant
from booking.forms import  ParticipantSmallForm

import logging
logger = logging.getLogger(__name__)


class ParticipantDetail(DetailView):
    model = Participant
    context_object_name = "participant"


class ParticipantCreate(CreateView):
    form_class = ParticipantSmallForm
    model = Participant

    def get_initial(self):

        event = get_object_or_404(Event, pk = self.kwargs.get('event_id'))    
        return { 'event': event.id,
                 'from_date': event.start_date,
                 'to_date': event.end_date  }

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ParticipantCreate, self).form_valid(form)


class ParticipantUpdate(UpdateView):
    form_class = ParticipantSmallForm
    model = Participant


class ParticipantDelete(DeleteView):
    model = Participant
    success_url = reverse_lazy('event_list')


class EventList(ListView):
    model = Event


class EventDetail(DetailView):
    model = Event

#    def get_object(self):
#        if self.request.GET.get('date',''):

booking/templates/booking/event_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

{% include 'booking/one_event_detail.html' %}

<i><a href="{% url 'event_list' %}">Alla händelser</a></i>
{% endblock %}

booking/templates/booking/event_list.html
{% extends "base.html" %}
{% load i18n %}
{% load avatar_tags %}
{% block content %}

<h1>Lista på händelster</h1>

{% for event in object_list %}
{% include 'booking/one_event_detail.html' %}

{% empty %}
    <b>No event yet.</b>
{% endfor %}


{% endblock %}

booking/templates/booking/one_event_detail.html
{% load avatar_tags %}
{% load sekizai_tags %}
{% load staticfiles %}

{% addtoblock "css" %}<link rel="stylesheet" type="text/css" href="{% static 'booking/css/booking.css' %}">{% endaddtoblock %}

<h2><a href="{% url 'event_detail' event.id %}">{{ event.name }}</a> 
    {% if event.participants %}
        {% if user.username not in event.participants %}
        <a class="button green" href="{% url 'participant_add' event.id %}">Anmäla dig!</a>
        {% endif %}

    {% else %}
        <a class="button green" href="{% url 'participant_add' event.id %}">Bli den första att anmäla dig!</a>
    {% endif %}</h2>
	<i>{{ event.start_date }} - {{ event.end_date }}</i>
	<p>{{ event.description }}</p>


    <div class="tabs">
        <ul>
            <li><a href="#tabs-all">Alla</a></li>
        {% for date in event.dates %}
            <li><a href="#tabs-{{ date|date:"Y-m-d" }}">{{ date }}</a></li>
        {% endfor %}
        </ul>
        <div class="clear"></div>
        <div class="bordered_box">
            <div id="tabs-all" >
                <div class="content_text"><p>
                {% for participant in event.participant_set.all %}
                    {% if participant.user == user %}
                    <div class="booking_participant myself"><a href="{% url 'participant_update' participant.id %}">{% avatar participant.user %}</a></div>
                    {% else %}
                    <div class="booking_participant">{% avatar participant.user %}</div>
                    {% endif %}
                {% endfor %}

                    <div class="clear"></div>

                </p>
                </div>
            </div>
            {% for this_date in event.dates %}
            <div id="tabs-{{ this_date|date:"Y-m-d" }}">
                <div class="content_text"><p>
                {% for participant in event.participant_set.all %}
                    {% if this_date >= participant.from_date and this_date <= participant.to_date %}
                        {% if participant.user == user %}
                        <div class="booking_participant"><a href="{% url 'participant_update' participant.id %}">{% avatar participant.user %}</a></div>
                        {% else %}
                        <div class="booking_participant">{% avatar participant.user %}</div>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                    <div class="clear"></div>
                    </p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

	<div class="clear"></div>

booking/templates/booking/participant_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<form method="post" >
    {% csrf_token %}
    Är du säker på att du skall avanmäla dig?
	<p>
		<a href="{% url 'participant_update' participant.id %}" class="button green">Avbryt</a>
 		<input type="submit" value="Tyvärr!" />
 	</p>
</form>

{% endblock %}

booking/templates/booking/participant_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

<h1>{{ user.first_name }} {{ user.last_name }}</h1>

{% if participant %}
<form action="{% url 'participant_update' participant.id %}">
<h1 class="regular brown bottom_line"><a href="{% url 'event_detail' participant.event.id %}">{{ participant.event.name }}</a></h1>
<p>Du är anmäld på {{ participant.event.name }} mellan <b>{{ participant.from_date }}</b> och <b>{{ participant.to_date }}</b>. Medverkan nivå: {{ participant.level }} <a href="{% url 'participant_update' participant.id %}" class="button blue">Ändra</a> </p>
{% endif %} 

{% endblock %}

booking/templates/booking/participant_form.html
{% extends "base.html" %}
{% load sekizai_tags %}
{% load i18n %}
{% block content %}

<h1>Anmälan</h1>
<form method ="POST"> 
    {% csrf_token %}

    {% if form.errors %}
            <div class="error">
                    <b>{% trans "Found some errors:" %}</b>
                    <ol>
                    {% for error in form.errors %}
                            <li><strong>{{ error|escape }}</strong></li>
                    {% endfor %}
                    </ol>
            </div>
    {% endif %}
    {% csrf_token %}
    {% for field in form.visible_fields %}
        {# Include the hidden fields in the form #}
            {% if forloop.first %}
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}
            {% endif %}
    
            <div class="field {% if field.errors %}field_error{% endif %}">
                    {{ field.label_tag }} {{ field }}
                    <i>{{ field.help_text }}</i>
                    {{ field.errors }}
            </div>
    {% endfor %}

    <input type="submit" value="Save" />
    {% if object.id %}
    <a href="{% url 'participant_delete' object.id %}" class="button red">Avboka</a>
    {% endif %}
</form>

{%  addtoblock "css" %}
    <style>
        .error, .field_error {
            color: red;

        }

        .error {
            margin-left: 20px;            
        }
    </style>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/jquery-ui.css" type="text/css" />
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.9.1.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui-1.10.3.js"></script>   
    <script type="text/javascript">
                // Implement the datepicker
     $(function() {
        $('#id_from_date').datepicker({ 'dateFormat': "yy-mm-dd" });
        $('#id_to_date').datepicker({ 'dateFormat': "yy-mm-dd" });
     });
    </script>
{% endaddtoblock %}
{% endblock %}

booking/templates/booking/plugin.html
{% include 'booking/one_event_detail.html'  with event=instance.event %}
<i><a href="{% url 'event_list'%}">Alla händelser</a></i>